services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  restate:
    image: docker.restate.dev/restatedev/restate:latest
    ports:
      - 9070:9070
      - 9071:9071
      - 8080:8080
