/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadsRouteImport } from './routes/api/uploads'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthAcceptInviteRouteImport } from './routes/_auth/accept-invite'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppSettingsOrganizationsIndexRouteImport } from './routes/_app/settings/organizations/index'
import { Route as ApiRestateV0SplatRouteImport } from './routes/api/restate/v0/$'
import { Route as AppSettingsOrganizationsOrganizationIdRouteImport } from './routes/_app/settings/organizations/$organizationId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsRoute = ApiUploadsRouteImport.update({
  id: '/api/uploads',
  path: '/api/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAcceptInviteRoute = AuthAcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => AuthRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsOrganizationsIndexRoute =
  AppSettingsOrganizationsIndexRouteImport.update({
    id: '/settings/organizations/',
    path: '/settings/organizations/',
    getParentRoute: () => AppRoute,
  } as any)
const ApiRestateV0SplatRoute = ApiRestateV0SplatRouteImport.update({
  id: '/api/restate/v0/$',
  path: '/api/restate/v0/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsOrganizationsOrganizationIdRoute =
  AppSettingsOrganizationsOrganizationIdRouteImport.update({
    id: '/settings/organizations/$organizationId',
    path: '/settings/organizations/$organizationId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AuthAcceptInviteRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/api/health': typeof ApiHealthRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/projects': typeof AppProjectsIndexRoute
  '/settings/organizations/$organizationId': typeof AppSettingsOrganizationsOrganizationIdRoute
  '/api/restate/v0/$': typeof ApiRestateV0SplatRoute
  '/settings/organizations': typeof AppSettingsOrganizationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AuthAcceptInviteRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/api/health': typeof ApiHealthRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/projects': typeof AppProjectsIndexRoute
  '/settings/organizations/$organizationId': typeof AppSettingsOrganizationsOrganizationIdRoute
  '/api/restate/v0/$': typeof ApiRestateV0SplatRoute
  '/settings/organizations': typeof AppSettingsOrganizationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/accept-invite': typeof AuthAcceptInviteRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/api/health': typeof ApiHealthRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/settings/organizations/$organizationId': typeof AppSettingsOrganizationsOrganizationIdRoute
  '/api/restate/v0/$': typeof ApiRestateV0SplatRoute
  '/_app/settings/organizations/': typeof AppSettingsOrganizationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/register'
    | '/api/health'
    | '/api/uploads'
    | '/api/auth/$'
    | '/projects'
    | '/settings/organizations/$organizationId'
    | '/api/restate/v0/$'
    | '/settings/organizations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/register'
    | '/api/health'
    | '/api/uploads'
    | '/api/auth/$'
    | '/projects'
    | '/settings/organizations/$organizationId'
    | '/api/restate/v0/$'
    | '/settings/organizations'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_auth/accept-invite'
    | '/_auth/login'
    | '/_auth/register'
    | '/api/health'
    | '/api/uploads'
    | '/api/auth/$'
    | '/_app/projects/'
    | '/_app/settings/organizations/$organizationId'
    | '/api/restate/v0/$'
    | '/_app/settings/organizations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiUploadsRoute: typeof ApiUploadsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRestateV0SplatRoute: typeof ApiRestateV0SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads': {
      id: '/api/uploads'
      path: '/api/uploads'
      fullPath: '/api/uploads'
      preLoaderRoute: typeof ApiUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/accept-invite': {
      id: '/_auth/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AuthAcceptInviteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings/organizations/': {
      id: '/_app/settings/organizations/'
      path: '/settings/organizations'
      fullPath: '/settings/organizations'
      preLoaderRoute: typeof AppSettingsOrganizationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/restate/v0/$': {
      id: '/api/restate/v0/$'
      path: '/api/restate/v0/$'
      fullPath: '/api/restate/v0/$'
      preLoaderRoute: typeof ApiRestateV0SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings/organizations/$organizationId': {
      id: '/_app/settings/organizations/$organizationId'
      path: '/settings/organizations/$organizationId'
      fullPath: '/settings/organizations/$organizationId'
      preLoaderRoute: typeof AppSettingsOrganizationsOrganizationIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppSettingsOrganizationsOrganizationIdRoute: typeof AppSettingsOrganizationsOrganizationIdRoute
  AppSettingsOrganizationsIndexRoute: typeof AppSettingsOrganizationsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppSettingsOrganizationsOrganizationIdRoute:
    AppSettingsOrganizationsOrganizationIdRoute,
  AppSettingsOrganizationsIndexRoute: AppSettingsOrganizationsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthAcceptInviteRoute: typeof AuthAcceptInviteRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAcceptInviteRoute: AuthAcceptInviteRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiUploadsRoute: ApiUploadsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRestateV0SplatRoute: ApiRestateV0SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
